name: Auto Update Files

on:
  repository_dispatch:
    types: [update_trigger]
  workflow_dispatch:
  schedule:
    - cron: '23 4 * * *'

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Setup repository cache
      uses: actions/cache@v3
      env:
        cache-name: swi-prolog-repositories
      with:
        path: ~/repos
        key: swi-prolog-repositories
    - name: Run update script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        nix develop . --command ./refresh.sh ~/repos
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automatic Update
